### ISSUE TITLE
Feedback for search, order and general UX

### ISSUE THREAD

**Issue by ronaldtveen** [BjornTheProgrammer/vue-simple-phone#1]
I think it is currently already pretty awesome. Came across this project through [daily.dev](https://dly.to/Sp49DKTb2zO)

Tried some of the examples and this is what makes me not use it as of just yet;

-----

I'm missing a search option in the country list. Try and search for the UK, it'll take you a couple of minutes because the display order of the countries is very odd too: 

<img width="212" alt="SCR-20241219-jfkl" src="https://github.com/user-attachments/assets/225a9b68-f723-41db-9875-0fad50e7c1c8" />

I'd like to be able to start typing the moment you open the dropdown and that it'll search by country code as well as country name.

-----

There are different formats for landlines and mobile numbers; For example mobile numbers in The Netherlands always start with "06". Would be great if that could be made an option too, to switch formats per country.

-----

Just my two cents. Hope you'll find this feedback helpful.

**Comment by BjornTheProgrammer** [comment]
Thank you for your feedback @ronaldtveen!

> I'd like to be able to start typing the moment you open the dropdown and that it'll search by country code as well as country name.

It makes a lot of sense to make an autocomplete. I can't believe I hadn't thought of it before. I'll add this in the next version of `Vue Simple Phone`.

> There are different formats for landlines and mobile numbers; For example mobile numbers in The Netherlands always start with "06". Would be great if that could be made an option too, to switch formats per country.

This sounds like a great idea, How would you recommend doing this? I could expose a prop that allows you to specify what kind of placeholder phone format you want, for example, a landline phone number. Or would you rather this be more granular, with an option of per country?

This feedback is really helpful!

edit: I'll also fix the order to be properly in alphabetical order.

**Comment by BjornTheProgrammer** [comment]
v1.1.0 should implement all of these suggestions and more! Thank you for your feedback! If you have any other issues, general feedback, or concerns, please let me know!
